model:
  input_dim: 3
  hidden_dim: 256
  num_layers: 3
  k: 20
  edge_k: 20
data:
  data_dir: data/processed
  val_split: 0.1
  num_workers: 4
training:
  num_epochs: 100
  batch_size: 32
  learning_rate: 0.001
  early_stopping_patience: 10
  checkpoint_dir: data/checkpoints
loss:
  lambda_c: 1.0
  lambda_e: 1.0
  lambda_o: 1.0

